#!/usr/bin/env bash

set -euo pipefail

VAULT_DIR=${VAULT_DIR:-"$HOME/Obsidian/spare skull"}
DATE="$(date -I)"
RELPATH="journal/$DATE.md"
ABSPATH="$VAULT_DIR/$RELPATH"

read_bool() {
	read -n1 -erp "${1^}? (y/N) " v
	if [[ $v == "y" ]]; then
	  read -r "$1" <<<true
  else
	  read -r "$1" <<<false
  fi
}

read_emote() {
	read -erp "${1^}? [:D :) :| :( :<] " v
	case $v in
		":D") read -r "$1" <<<5;;
		":)") read -r "$1" <<<4;;
		":|") read -r "$1" <<<3;;
		":(") read -r "$1" <<<2;;
		":<") read -r "$1" <<<1;;
		"-") read -r "$1" <<<"";;
		*)
		  # Invalid input, try again
			read_emote "$1"
	esac
}

create_journal_entry() {
	declare itchy sleep bleeding weeping cracked flaking dry work mood

	echo ":: POEM Scores"
	read_bool itchy
	read_bool sleep
	read_bool bleeding
	read_bool weeping
	read_bool cracked
	read_bool flaking
	read_bool dry
	echo ":: Check-in"
	read_emote work
	read_emote mood

	# Create and open the file with Obsidian
	# This avoids a problem where `obsidian open` doesn't always "notice" the new
	# file after the heredoc pipe below.
	obsidian create open "path=$RELPATH,open"
	# Hide file properties for journalling
	obsidian command id=editor:fold-all
	cat <<EOF > "$ABSPATH"
---
POEM.Itchy: $itchy
POEM.Sleep: $sleep
POEM.Bleeding: $bleeding
POEM.Weeping: $weeping
POEM.Cracked: $cracked
POEM.Flaking: $flaking
POEM.Dry: $dry
Work: $work
Mood: $mood
date: $DATE
---
EOF
}

if [[ -f "$ABSPATH" ]]; then
	1>&2 echo "Found today's journal"
else
	create_journal_entry
fi

open -a obsidian
