#! /usr/bin/env python3
'''
Get leaf directories below current directory
'''

import os

def nonhidden_leaves(startdir):
    '''
    Get nonhidden leaf directories below a directory
    '''
    # Walk skipping hidden directories
    # https://stackoverflow.com/questions/13454164/os-walk-without-hidden-folders#13454267
    for root, dirs, files in os.walk(startdir):
        files = [f for f in files if not f.startswith('.')]
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        if dirs == []:
            yield root

def main():
    '''
    Print out leaves
    '''
    for leaf in nonhidden_leaves(os.getcwd()):
        print(leaf)

if __name__ == '__main__':
    main()
