#!/usr/bin/env python3

import argparse
from urllib.parse import quote

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('text')

    text = parser.parse_args().text
    print(quote(text))
