#!/bin/bash
# Get latest terraform

set -euo pipefail

LATEST_RELEASE=$(curl https://api.github.com/repos/hashicorp/terraform/releases/latest 2>/dev/null | jq --raw-output '.tag_name' | cut -c 2-)
BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ ! -d "$BIN_DIR" ]]; then
    >&2 echo No such directory: "$BIN_DIR"
    exit 1
fi

if [[ -x $(which terraform) ]]; then
    TF_VERSION=$(terraform --version 2>/dev/null | head -n1 | sed 's/^Terraform v//')
    if [[ $TF_VERSION == "$LATEST_RELEASE" ]]; then
        echo "Already up to date: Terraform v$TF_VERSION"
        exit 0
    fi
fi

echo "Installing Terraform v$LATEST_RELEASE to $BIN_DIR"
curl "https://releases.hashicorp.com/terraform/${LATEST_RELEASE}/terraform_${LATEST_RELEASE}_linux_amd64.zip" | gunzip - > "$BIN_DIR/terraform"
chmod 775 "${BIN_DIR}/terraform"
